### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by acoffman** [griffithlab/civic-v2#394]
- [x] Put V1 in Read Only mode (nullifying sessions, remove login)
- [x] Add "Maintenance mode/V2 is coming" text to V1
- [x] Deploy V1
- [x] Copy Data releases from v1 -> v2 AWS instance
- [x] Take a final database snapshot of V1
- [x] Copy DB snapshot locally and back-up
- [x] Create an empty local V1 schema database
- [x] Load final v1 data dump
- [x] Run all v2 migrations against new database  (including the suggested change -> revision one yet to be merged)
- [x] Backfill originating object on comments (https://github.com/griffithlab/civic-v2/issues/107)
- [x] Double check that all revisions have an originating object/action names are updated to "revision"
- [x] Clean up empty comments
- [x] Dump database
- [x] Copy data dump to V2 production and load it in
- [x] Scrape User profile images and (see script in golive issue)
- [x] Refresh SQL views and Run initial elasticsearch indexing 
- [x] Smoke test of frontend (table sorting and filtering, browsing around, etc)
- [x] Create 2.0 github release and verify that deploy succeeds
- [x] Have Obi or Malachi update the DNS entries: civicdb.org -> new AWS IP, v1.civicdb.org -> old AWS IP
- [x] Run certbot
- [x] Update NGINX config
- [x] Restart NGINX
- [x]  bring over Organization images 
- [x] 🍸
