### ISSUE TITLE
MP Post-Release Checklist

### ISSUE THREAD

**Issue by acoffman** [griffithlab/civic-v2#670]
- [ ] common name for MP
- [ ] Remove association of assertions & evidence with variants
- [ ] Rename postgres table drugs->therapies
- [ ] Activerecord model rename 
- [ ] Port `field` on revisions from `drug_ids` to `therapy_ids`
- [ ] Change column name in postgres to `significance`
- [ ] Rename custom icons civic:drug -> civic:therap
