### ISSUE TITLE
MP Rollout Checklist

### ISSUE THREAD

**Issue by acoffman** [griffithlab/civic-v2#691]
- [x] Write news item announcing MPs 
- [x] Put up maintenance page/put civic in read only mode
- [x] Take a database snapshot
- [x] Curate/prepare release notes
- [x] Deploy Release
- [x] Run migration script: https://gist.github.com/acoffman/86b8833e10506b98b16a116f75d8ddba
- [x] Test civicpy locally pointing to prod
- [x] Push new civicpy release to pypi
- [x] Update civicpy on production
- [x] Generate pkl cache and vcf
- [x] Publish docs site
- [x] #693
